version: "3.3"
services:
  sonar:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: sonar_ecocode_ios
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    depends_on:
      - db
    environment:
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
    volumes:
      - type: bind
        source: ./sonar-ios-plugin/target/ecodecode-sonar-ios-plugin-1.0.2-SNAPSHOT.jar
        target: /opt/sonarqube/extensions/plugins/ecodecode-sonar-ios-plugin-1.0.2-SNAPSHOT.jar
      - "logs:/opt/sonarqube/logs"
      - "data:/opt/sonarqube/data"
  db:
    image: postgres:12
    container_name: postgresql_ecocode_ios
    networks:
      - sonarnet
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
      PGDATA: pg_data:/var/lib/postgresql/data/pgdata

networks:
  sonarnet:
    driver: bridge

volumes:
  data:
  logs:
  extensions:
  pg_data:
